// Code generated by goctl. DO NOT EDIT.
package types

type UserRegisterRequest struct {
	Name     string `json:"name"`
	Password string `json:"password"`
	Mail     string `json:"mail"`
	Code     string `json:"code"`
}

type UserRegisterReply struct {
	Id      int64  `json:"id"`
	Name    string `json:"name"`
	Mail    string `json:"mail"`
	Success bool   `json:"success"`
	Error   string `json:"error"`
}

type LonginRequest struct {
	Name     string `json:"name"`
	Password string `json:"password"`
}

type LoginReply struct {
	Token string `json:"token"`
}

type UserDetailRequest struct {
	Identity string `json:"identity"`
}

type UserDetailReply struct {
	Name  string `json:"name"`
	Email string `json:"email"`
}

type MailCodeSendRequest struct {
	Email string `json:"email"`
}

type MailCodeSendReply struct {
}

type FileUploadRequest struct {
	Hash string `json:"hash,optional"`
	Name string `json:"name,optional"`
	Ext  string `json:"ext,optional"`
	Size string `json:"size,optional"`
	Path string `json:"path,optional"`
}

type FileUploadReply struct {
	Identity string `json:"identity"`
}
