// Code generated by goctl. DO NOT EDIT.
package types

type LonginRequest struct {
	Name     string `json:"name"`
	Password string `json:"Password"`
}

type LoginReply struct {
	Token string `json:"token"`
}

type UserDetailRequest struct {
	Identity string `json:"identity"`
}

type UserDetailReply struct {
	Name  string `json:"name"`
	Email string `json:"email"`
}
