// Code generated by goctl. DO NOT EDIT.
package types

type UserRepostitorySaveRequest struct {
	ParentId            int    `json:"parentId"`
	Repository_identity string `json:"repositoryIdentity"`
	Ext                 string `json:"ext"`
	Name                string `json:"name"`
}

type UserRepostitorySaveReply struct {
}

type UserFileListRequest struct {
	Id   int64 `json:"id"`
	Page int64 `json:"page"`
	Size int64 `json:"size"`
}

type UserFileListReply struct {
	List  []*UserFile `json:"list"`
	Count int64       `json:"count"`
}

type UserFile struct {
	Id                  int64  `json:"id"`
	Identity            string `json:"identity"`
	RepostitoryIdentity string `json:"repostitoryIdentity"`
	Ext                 string `json:"ext"`
	Name                string `json:"name"`
	Size                int64  `json:"size"`
	Path                string `json:"path"`
}

type UserRegisterRequest struct {
	Name     string `json:"name"`
	Password string `json:"password"`
	Mail     string `json:"mail"`
	Code     string `json:"code"`
}

type UserRegisterReply struct {
	Id      int64  `json:"id"`
	Name    string `json:"name"`
	Mail    string `json:"mail"`
	Success bool   `json:"success"`
	Error   string `json:"error"`
}

type LonginRequest struct {
	Name     string `json:"name"`
	Password string `json:"password"`
}

type LoginReply struct {
	Token string `json:"token"`
}

type UserDetailRequest struct {
	Identity string `json:"identity"`
}

type UserDetailReply struct {
	Name  string `json:"name"`
	Email string `json:"email"`
}

type MailCodeSendRequest struct {
	Email string `json:"email"`
}

type MailCodeSendReply struct {
}

type FileUploadRequest struct {
	Hash string `json:"hash,optional"`
	Name string `json:"name,optional"`
	Ext  string `json:"ext,optional"`
	Size string `json:"size,optional"`
	Path string `json:"path,optional"`
}

type FileUploadReply struct {
	Identity string `json:"identity"`
	Ext      string `json:"ext"`
	Name     string `json:"name"`
}
